### ISSUE TITLE
Do not fail if a requirement is not fulfilled. Make them "soft" requirements

### ISSUE THREAD

**Issue by schaubl** [nuvlabox/system-manager#16]
For example, do not stop NuvlaBox Engine if Swarm mode is not enabled but instead continue in a degraded mode and possibly warn the user.

**Comment by cjdcordeiro** [comment]
Draft identification of threats and impact on NuvlaBox Engine containers:

<table>
<tr>
	<th colspan='3' >Threat</th>
	<th colspan='9' >NuvlaBox Engine containers</th>

</tr>
<tr align='center'>
	<td><b><i>ID</td>
	<td colspan='2'><b><i>Description</td>
	<td><b><i>system-manager</td>
	<td><b><i>agent</td>
	<td><b><i>management-api</td>
	<td><b><i>compute-api</td>
	<td><b><i>network-manager</td>
	<td><b><i>vpn-client</td>
	<td><b><i>traefik</td>
	<td><b><i>mosquitto</td>
	<td><b><i>peripheral-manager-*</td>
</tr>
<tr>
	<th colspan='12' align='left'>Installation Requirements</th>

</tr>
<tr>
	<td>NB-2020-REQ-CPU*</td>
	<td colspan='2'>The target device does not meet the CPU requirements for installing the NuvlaBox Engine</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
</tr>
<tr>
	<td>NB-2020-REQ-RAM*</td>
	<td colspan='2'>The target device does not meet the Memory requirements for installing the NuvlaBox Engine</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
</tr>
<tr>
	<td>NB-2020-REQ-DISK*</td>
        <td colspan='2'>The target device does not meet the Disk requirements for installing the NuvlaBox Engine</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
</tr>
<tr>
	<td>NB-2020-REQ-DOCKER*</td>
        <td colspan='2'>The Docker version on the target device does not meet the requirements for installing the NuvlaBox Engine</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
	<td>Stop</td>
</tr>
</table>

* ignored when `SKIP_MINIMUM_REQUIREMENTS` is set

**Comment by cjdcordeiro** [comment]
refer to https://github.com/nuvlabox/agent/issues/42 for implementation

**Comment by schaubl** [comment]
I think we should not do`**`.
So that in the case where `docker swarm init` fail during the auto-install, the NuvlaBox will appear in Nuvla (in a degraded mode/state) and it will allow to connect to it to debug the issue.

**Comment by cjdcordeiro** [comment]
`**` is not optional, since we need swarm to initialize the NB, due to the overlay network. And it's a reasonable approach - why would we let a NB start in a faulty state? better fix first

**Comment by cjdcordeiro** [comment]
@schaubl do you think this is still applicable? we already have the SKIP_REQUIREMENTS flag and the system-manager is not longer killing any containers, on any arror

**Comment by schaubl** [comment]
@cjdcordeiro If the system-manager is no longer killing any containers, I this this issue can be close.
