### ISSUE TITLE
[FEATURE] on startup failure report which system requirement is not met

### ISSUE THREAD

**Issue by konstan** [nuvlabox/system-manager#29]
**Is your feature request related to a problem? Please describe.**

In case minimum requirements for installation are not met, the system manager prints the following and bails out.
```
system-manager_1   | ERROR - run.py/run/requirements_check - System does not meet the minimum requirements!
system-manager_1   | Cannot continue...
```
The actual requirement that is not met is not specified in the error message.

**Describe the solution you'd like**

The requirements that are not met are logged.

**Additional context**

```
system-manager_1   | ERROR - run.py/run/requirements_check - System does not meet the minimum requirements!
system-manager_1   | Cannot continue...
```

**Comment by cjdcordeiro** [comment]
implemented in https://github.com/nuvlabox/system-manager/releases/tag/2.2.0
